name: treksync_trip_planner
description: "Trip Organizer and Planning App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ^17.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
